package projetomaker;

import DBA.ProdutoDAO;
import javax.swing.JOptionPane;
import produtos.Monitores;

public class TelaDadosMonitor extends javax.swing.JFrame {

  // Atributos da clsses para ficarem disponíveis para todos os métodos
  int operacao;
  int codigo;
  
  // Construtor da janela alterado para receber o tipo de operação (1, 2 ou 3)
 // e o codigo do registro no banco, se codigo = 0 é uma inclusão 
  public TelaDadosMonitor(int operacao, int codigo) {
      
    initComponents();
    // repassa os dados recebidos para os atributos da classe
    this.operacao = operacao;
    this.codigo = codigo;
    if (operacao == 1) {
      // Determina o título da janela para uma inclusão
      lb1.setText("Inclusão");
        }
    if (operacao == 2) {
      // Determina o título da janela para uma alteração
      lb1.setText("Editar");
      // Cria um objeto monitores para receber os dados da consulta
      Monitores ml = new Monitores();
      // Cria um objeto ProdutoDAO para uso dos métodos de acesso
      // ao banco para os monitores
      ProdutoDAO pd = new ProdutoDAO();
      // Realiza a busca no Banco os dados do registro do monitor
      // através do codigo
      ml = pd.buscarMonitor(codigo);
      // Preenche as caixas de texto com os dados do monitor
      txtNome.setText(ml.getNome());
      txtMarca.setText(ml.getMarca());
      txtPreco.setText(String.valueOf(ml.getPreco()));
      txtFreq.setText(String.valueOf(ml.getFreq()));
      txtPol.setText(String.valueOf(ml.getPol()));
      txtEntra.setText(String.valueOf(ml.getEntradas()));
    }
    if (operacao == 3) {
      // Determina o título da janela para uma exclusão
      lb1.setText("Excluir");
      // Cria um objeto monitores para receber os dados da consulta
      Monitores ml = new Monitores();
      // Cria um objeto ProdutoDAO para uso dos métodos de acesso
      // ao banco para os monitores
      ProdutoDAO pd = new ProdutoDAO();
      // Realiza a busca no Banco os dados do registro do monitor
      // através do codigo
      ml = pd.buscarMonitor(codigo);
      // Preenche as caixas de texto com os dados do monitor
      txtNome.setText(ml.getNome());
      txtMarca.setText(ml.getMarca());
      txtPreco.setText(String.valueOf(ml.getPreco()));
      txtFreq.setText(String.valueOf(ml.getFreq()));
      txtPol.setText(String.valueOf(ml.getPol()));
      txtEntra.setText(String.valueOf(ml.getEntradas()));
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPol = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFreq = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtEntra = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lb1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 204));

        jPanel1.setBackground(new java.awt.Color(108, 100, 139));

        jPanel2.setBackground(new java.awt.Color(107, 186, 167));

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Marca");

        txtMarca.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtMarca.setText(" ");
        txtMarca.setAutoscrolls(false);
        txtMarca.setMargin(new java.awt.Insets(0, 0, 0, 0));
        txtMarca.setMaximumSize(new java.awt.Dimension(56, 56));
        txtMarca.setMinimumSize(new java.awt.Dimension(56, 56));

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Nome");

        txtNome.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNome.setText(" ");
        txtNome.setAutoscrolls(false);
        txtNome.setMargin(new java.awt.Insets(0, 0, 0, 0));
        txtNome.setMaximumSize(new java.awt.Dimension(56, 56));
        txtNome.setMinimumSize(new java.awt.Dimension(56, 56));

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Preço");

        txtPreco.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPreco.setText(" ");
        txtPreco.setAutoscrolls(false);
        txtPreco.setMargin(new java.awt.Insets(0, 0, 0, 0));
        txtPreco.setMaximumSize(new java.awt.Dimension(56, 56));
        txtPreco.setMinimumSize(new java.awt.Dimension(56, 56));

        jLabel8.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("Polegadas");

        txtPol.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPol.setText(" ");
        txtPol.setAutoscrolls(false);
        txtPol.setMargin(new java.awt.Insets(0, 0, 0, 0));
        txtPol.setMaximumSize(new java.awt.Dimension(56, 56));
        txtPol.setMinimumSize(new java.awt.Dimension(56, 56));

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Frequência");

        txtFreq.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtFreq.setText(" ");
        txtFreq.setAutoscrolls(false);
        txtFreq.setMargin(new java.awt.Insets(0, 0, 0, 0));
        txtFreq.setMaximumSize(new java.awt.Dimension(56, 56));
        txtFreq.setMinimumSize(new java.awt.Dimension(56, 56));

        jLabel9.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("Entrada");

        txtEntra.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtEntra.setText(" ");
        txtEntra.setAutoscrolls(false);
        txtEntra.setMargin(new java.awt.Insets(0, 0, 0, 0));
        txtEntra.setMaximumSize(new java.awt.Dimension(56, 56));
        txtEntra.setMinimumSize(new java.awt.Dimension(56, 56));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFreq, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtMarca, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                            .addComponent(txtPol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtEntra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtPol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtFreq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(txtEntra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(182, 161, 158));
        jPanel3.setMaximumSize(new java.awt.Dimension(358, 46));
        jPanel3.setMinimumSize(new java.awt.Dimension(358, 46));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetomaker/Pete Linforth.jpg"))); // NOI18N

        jPanel4.setBackground(new java.awt.Color(251, 161, 0));

        lb1.setBackground(new java.awt.Color(251, 161, 0));
        lb1.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        lb1.setForeground(new java.awt.Color(255, 255, 255));
        lb1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetomaker/monitor_icon-icons.com_64979.png"))); // NOI18N
        lb1.setText("INCLUIR");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(lb1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jButton1.setBackground(java.awt.Color.orange);
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 153, 255));
        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jButton1)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(141, 141, 141))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       // TODO add your handling code here:
       if (operacao == 1) { // Inclusão
        // Cria um objeto monitor para receber os dados da do preenchimento 
        // da tela
        Monitores m1 = new Monitores();
        // Cria um objeto ProdutoDAO para uso dos métodos de acesso
        // ao banco para os Monitores
        ProdutoDAO pd = new ProdutoDAO();
        // Determina os valores dos atributos do objeto monitor, com os dados
        // preenchidos na tela
        // o codigo é gerado automaticamente pelo Access
        m1.setNome      (                       txtNome.getText().trim());
        m1.setMarca     (                       txtMarca.getText().trim());
        m1.setPreco     (Double.parseDouble (   txtPreco.getText().trim()));
        m1.setFreq      (Double.parseDouble (   txtFreq.getText().trim()));
        m1.setPol       (Double.parseDouble (   txtPol.getText().trim()));
        m1.setEntradas  (Integer.parseInt   (   txtEntra.getText().trim()));
        m1.getEstoque().setQtdEstoque(0);
        // Verifica se a operação de inserção obteve sucesso
        if (pd.inserirMonitor(m1)) {
          String mensagem = "Monitor Inserido!";
          JOptionPane.showMessageDialog(null, mensagem);
          this.dispose();
        }
      } else if (operacao == 2) { // Alteração
        // Cria um objeto monitor para receber os dados da do preenchimento 
        // da tela
        Monitores ml = new Monitores();
        // Cria um objeto ProdutoDAO para uso dos métodos de acesso
        // ao banco para os monitores
        ProdutoDAO pd = new ProdutoDAO();
        // Determina os valores dos atributos do objeto monitor, com os dados
        // preenchidos na tela
        // o codigo irá ser usado para determinar o registro a ser alterado
        ml.setCodigo    (                                         codigo);
        ml.setNome      (                       txtNome.getText().trim());
        ml.setMarca     (                       txtMarca.getText().trim());
        ml.setPreco     (Double.parseDouble (   txtPreco.getText().trim()));
        ml.setFreq      (Double.parseDouble (   txtFreq.getText().trim()));
        ml.setPol       (Double.parseDouble (   txtPol.getText().trim()));
        ml.setEntradas  (Integer.parseInt   (   txtEntra.getText().trim()));
        // Verifica se a operação de alteração obteve sucesso
        if (pd.alterarMonitor(ml)) {
          String mensagem = "Monitor alterado!";
          JOptionPane.showMessageDialog(null, mensagem);
          this.dispose();
        }
      } else if (operacao == 3) { // Exclusão
        // Cria um objeto monitor para receber os dados da do preenchimento 
        // da tela
        Monitores ml = new Monitores();
        // Cria um objeto ProdutoDAO para uso dos métodos de acesso
        // ao banco para os monitores
        ProdutoDAO pd = new ProdutoDAO();
        // Determina os valores dos atributos do objeto monitor, com os dados
        // preenchidos na tela
        // o codigo irá ser usado para determinar o registro a ser alterado
        ml.setCodigo    (                                         codigo);
        ml.setNome      (                       txtNome.getText().trim());
        ml.setMarca     (                       txtMarca.getText().trim());
        ml.setPreco     (Double.parseDouble (   txtPreco.getText().trim()));
        ml.setFreq      (Double.parseDouble (   txtFreq.getText().trim()));
        ml.setPol       (Double.parseDouble (   txtPol.getText().trim()));
        ml.setEntradas  (Integer.parseInt   (   txtEntra.getText().trim()));
        // Verifica se a operação de exclusão obteve sucesso
        if (pd.excluirMonitor(ml)) {
          String mensagem = "Monitor excluído!";
          JOptionPane.showMessageDialog(null, mensagem);
        }
        this.dispose();
      }   
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDadosMonitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDadosMonitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDadosMonitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDadosMonitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDadosMonitor(0,0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lb1;
    private javax.swing.JTextField txtEntra;
    private javax.swing.JTextField txtFreq;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPol;
    private javax.swing.JTextField txtPreco;
    // End of variables declaration//GEN-END:variables
}
