package projetomaker;

import DBA.CompraDAO;
import DBA.ProdutoDAO;
import javax.swing.JOptionPane;
import administativo.compra;
import produtos.*;

public class TelaDadosReposicao extends javax.swing.JFrame {

  // Atributos da clsses para ficarem disponíveis para todos os métodos
  int operacao;
  int codigo;
  
  // Construtor da janela alterado para receber o tipo de operação (1, 2 ou 3)
 // e o codigo do registro no banco, se codigo = 0 é uma solicitação
  public TelaDadosReposicao(int operacao, int codigo) {
      
    initComponents();
    // repassa os dados recebidos para os atributos da classe
    this.operacao = operacao;
    this.codigo = codigo;
    if (operacao == 1) {
      // Determina o título da janela para uma solicitação
      lb1.setText("Solicitar Monitor");
      Monitores ml = new Monitores();
      ProdutoDAO pd = new ProdutoDAO();
      ml = pd.buscarMonitor(codigo);
      txtCodigoProduto.setText(String.valueOf(ml.getCodigo()));
      txtNome.setText(ml.getNome());
        }
    if (operacao == 2) {
      // Determina o título da janela para um recebimento
      lb1.setText("Receber Monitor");
      // Cria um objeto compra para receber os dados da consulta
      compra cl = new compra();
      // Cria um objeto CompraDAO para uso dos métodos de acesso
      // ao banco para as compras
      CompraDAO cd = new CompraDAO();
      // Realiza a busca no Banco os dados do registro da compra
      // através do codigo
      cl = cd.buscarCompra(codigo);
      // Preenche as caixas de texto com os dados da compra
      txtCodigoProduto.setText(String.valueOf(cl.getCodigoProduto()));
      txtNome.setText(cl.getNome());
      txtCodigoFornecedor.setText(String.valueOf(cl.getCodigoFornecedor()));
      txtFornecedor.setText(cl.getFornecedor());
      txtQuantidade.setText(String.valueOf(cl.getQtd()));
    }
    if (operacao == 3) {
      // Determina o título da janela para uma solicitação
      lb1.setText("Solicitar Mouse");
      Mouses mol = new Mouses();
      ProdutoDAO pd = new ProdutoDAO();
      mol = pd.buscarMouse(codigo);
      txtCodigoProduto.setText(String.valueOf(mol.getCodigo()));
      txtNome.setText(mol.getNome());
        }
    if (operacao == 4) {
      // Determina o título da janela para um recebimento
      lb1.setText("Receber Mouse");
      // Cria um objeto compra para receber os dados da consulta
      compra cl = new compra();
      // Cria um objeto CompraDAO para uso dos métodos de acesso
      // ao banco para as compras
      CompraDAO cd = new CompraDAO();
      // Realiza a busca no Banco os dados do registro da compra
      // através do codigo
      cl = cd.buscarCompra(codigo);
      // Preenche as caixas de texto com os dados da compra
      txtCodigoProduto.setText(String.valueOf(cl.getCodigoProduto()));
      txtNome.setText(cl.getNome());
      txtCodigoFornecedor.setText(String.valueOf(cl.getCodigoFornecedor()));
      txtFornecedor.setText(cl.getFornecedor());
      txtQuantidade.setText(String.valueOf(cl.getQtd()));
    }
    if (operacao == 5) {
      // Determina o título da janela para uma solicitação
      lb1.setText("Solicitar Teclado");
      Teclados tl = new Teclados();
      ProdutoDAO pd = new ProdutoDAO();
      tl = pd.buscarTeclado(codigo);
      txtCodigoProduto.setText(String.valueOf(tl.getCodigo()));
      txtNome.setText(tl.getNome());
        }
    if (operacao == 6) {
      // Determina o título da janela para um recebimento
      lb1.setText("Receber Teclado");
      // Cria um objeto compra para receber os dados da consulta
      compra cl = new compra();
      // Cria um objeto CompraDAO para uso dos métodos de acesso
      // ao banco para as compras
      CompraDAO cd = new CompraDAO();
      // Realiza a busca no Banco os dados do registro da compra
      // através do codigo
      cl = cd.buscarCompra(codigo);
      // Preenche as caixas de texto com os dados da compra
      txtCodigoProduto.setText(String.valueOf(cl.getCodigoProduto()));
      txtNome.setText(cl.getNome());
      txtCodigoFornecedor.setText(String.valueOf(cl.getCodigoFornecedor()));
      txtFornecedor.setText(cl.getFornecedor());
      txtQuantidade.setText(String.valueOf(cl.getQtd()));
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCodigoFornecedor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCodigoProduto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFornecedor = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lb1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 204));

        jPanel1.setBackground(new java.awt.Color(108, 100, 139));

        jPanel2.setBackground(new java.awt.Color(107, 186, 167));

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Codigo Produto");

        txtNome.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNome.setText(" ");
        txtNome.setAutoscrolls(false);
        txtNome.setMargin(new java.awt.Insets(0, 0, 0, 0));
        txtNome.setMaximumSize(new java.awt.Dimension(56, 56));
        txtNome.setMinimumSize(new java.awt.Dimension(56, 56));

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Codigo Fornecedor");

        txtCodigoFornecedor.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCodigoFornecedor.setText(" ");
        txtCodigoFornecedor.setAutoscrolls(false);
        txtCodigoFornecedor.setMargin(new java.awt.Insets(0, 0, 0, 0));
        txtCodigoFornecedor.setMaximumSize(new java.awt.Dimension(56, 56));
        txtCodigoFornecedor.setMinimumSize(new java.awt.Dimension(56, 56));

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Quantidade");

        txtQuantidade.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtQuantidade.setText(" ");
        txtQuantidade.setAutoscrolls(false);
        txtQuantidade.setMargin(new java.awt.Insets(0, 0, 0, 0));
        txtQuantidade.setMaximumSize(new java.awt.Dimension(56, 56));
        txtQuantidade.setMinimumSize(new java.awt.Dimension(56, 56));

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Nome");

        txtCodigoProduto.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCodigoProduto.setText(" ");
        txtCodigoProduto.setAutoscrolls(false);
        txtCodigoProduto.setMargin(new java.awt.Insets(0, 0, 0, 0));
        txtCodigoProduto.setMaximumSize(new java.awt.Dimension(56, 56));
        txtCodigoProduto.setMinimumSize(new java.awt.Dimension(56, 56));

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Fornecedor");

        txtFornecedor.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtFornecedor.setText(" ");
        txtFornecedor.setAutoscrolls(false);
        txtFornecedor.setMargin(new java.awt.Insets(0, 0, 0, 0));
        txtFornecedor.setMaximumSize(new java.awt.Dimension(56, 56));
        txtFornecedor.setMinimumSize(new java.awt.Dimension(56, 56));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtCodigoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txtCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCodigoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(182, 161, 158));
        jPanel3.setMaximumSize(new java.awt.Dimension(358, 46));
        jPanel3.setMinimumSize(new java.awt.Dimension(358, 46));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetomaker/Pete Linforth.jpg"))); // NOI18N

        jPanel4.setBackground(new java.awt.Color(251, 161, 0));

        lb1.setBackground(new java.awt.Color(251, 161, 0));
        lb1.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        lb1.setForeground(new java.awt.Color(255, 255, 255));
        lb1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetomaker/reposicao.png"))); // NOI18N
        lb1.setText("INCLUIR");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(lb1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jButton1.setBackground(java.awt.Color.orange);
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 153, 255));
        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jButton1)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(156, 156, 156))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       // TODO add your handling code here:
       if (operacao == 1) { // Solicitar Monitor
        // Cria um objeto compra para receber os dados da do preenchimento 
        // da tela
        compra c1 = new compra();
        // Cria um objeto CompraDAO para uso dos métodos de acesso
        // ao banco para as compras
        CompraDAO cd = new CompraDAO();
        // Determina os valores dos atributos do objeto compra, com os dados
        // preenchidos na tela
        // o codigo é gerado automaticamente pelo Access
        c1.setCodigoProduto    (Integer.parseInt   (txtCodigoProduto.getText().trim()));
        c1.setNome             (                    txtNome.getText().trim());
        c1.setCodigoFornecedor (Integer.parseInt   (txtCodigoFornecedor.getText().trim()));
        c1.setFornecedor       (                    txtFornecedor.getText().trim());
        c1.setQtd              (Integer.parseInt   (txtQuantidade.getText().trim()));
        // Verifica se a operação de solicitação obteve sucesso
        if (cd.solicitarMonitor(c1)) {
          String mensagem = "Requisição de compra enviada!";
          JOptionPane.showMessageDialog(null, mensagem);
          this.dispose();
        }
      } else if (operacao == 2) { // Receber Monitor
        // Cria um objeto compra para receber os dados da do preenchimento 
        // da tela
        compra cl = new compra();
        // Cria um objeto CompraDAO para uso dos métodos de acesso
        // ao banco para os compras
        CompraDAO cd = new CompraDAO();
        // Determina os valores dos atributos do objeto compra, com os dados
        // preenchidos na tela
        // o codigo irá ser usado para determinar o registro a ser alterado
        cl.setCodigo      (                                        codigo);
        cl.setCodigoProduto    (Integer.parseInt   (txtCodigoProduto.getText().trim()));
        cl.setNome             (                    txtNome.getText().trim());
        cl.setCodigoFornecedor (Integer.parseInt   (txtCodigoFornecedor.getText().trim()));
        cl.setFornecedor       (                    txtFornecedor.getText().trim());
        cl.setQtd              (Integer.parseInt   (txtQuantidade.getText().trim()));
        
        Monitores m1 = new Monitores();
        ProdutoDAO pd = new ProdutoDAO();
        m1 = pd.buscarMonitor(cl.getCodigoProduto());
        
        // Verifica se a operação de alteração obteve sucesso
        if (cd.receberMonitor(cl, m1)) {
          String mensagem = "Estoque atualizado!";
          JOptionPane.showMessageDialog(null, mensagem);
          this.dispose();
        }
      } else if (operacao == 3) { // Solicitar Mouse
        // Cria um objeto compra para receber os dados da do preenchimento 
        // da tela
        compra c1 = new compra();
        // Cria um objeto CompraDAO para uso dos métodos de acesso
        // ao banco para as compras
        CompraDAO cd = new CompraDAO();
        // Determina os valores dos atributos do objeto compra, com os dados
        // preenchidos na tela
        // o codigo é gerado automaticamente pelo Access
        c1.setCodigoProduto    (Integer.parseInt   (txtCodigoProduto.getText().trim()));
        c1.setNome             (                    txtNome.getText().trim());
        c1.setCodigoFornecedor (Integer.parseInt   (txtCodigoFornecedor.getText().trim()));
        c1.setFornecedor       (                    txtFornecedor.getText().trim());
        c1.setQtd              (Integer.parseInt   (txtQuantidade.getText().trim()));
        // Verifica se a operação de solicitação obteve sucesso
        if (cd.solicitarMouse(c1)) {
          String mensagem = "Requisição de compra enviada!";
          JOptionPane.showMessageDialog(null, mensagem);
          this.dispose();
        }
      } else if (operacao == 4) { // Receber Mouse
        // Cria um objeto compra para receber os dados da do preenchimento 
        // da tela
        compra cl = new compra();
        // Cria um objeto CompraDAO para uso dos métodos de acesso
        // ao banco para os compras
        CompraDAO cd = new CompraDAO();
        // Determina os valores dos atributos do objeto compra, com os dados
        // preenchidos na tela
        // o codigo irá ser usado para determinar o registro a ser alterado
        cl.setCodigo      (                                        codigo);
        cl.setCodigoProduto    (Integer.parseInt   (txtCodigoProduto.getText().trim()));
        cl.setNome             (                    txtNome.getText().trim());
        cl.setCodigoFornecedor (Integer.parseInt   (txtCodigoFornecedor.getText().trim()));
        cl.setFornecedor       (                    txtFornecedor.getText().trim());
        cl.setQtd              (Integer.parseInt   (txtQuantidade.getText().trim()));
        
        Mouses mo1 = new Mouses();
        ProdutoDAO pd = new ProdutoDAO();
        mo1 = pd.buscarMouse(cl.getCodigoProduto());
        
        // Verifica se a operação de alteração obteve sucesso
        if (cd.receberMouse(cl, mo1)) {
          String mensagem = "Estoque atualizado!";
          JOptionPane.showMessageDialog(null, mensagem);
          this.dispose();
        }
      } else if (operacao == 5) { // Solicitar Teclado
        // Cria um objeto compra para receber os dados da do preenchimento 
        // da tela
        compra c1 = new compra();
        // Cria um objeto CompraDAO para uso dos métodos de acesso
        // ao banco para as compras
        CompraDAO cd = new CompraDAO();
        // Determina os valores dos atributos do objeto compra, com os dados
        // preenchidos na tela
        // o codigo é gerado automaticamente pelo Access
        c1.setCodigoProduto    (Integer.parseInt   (txtCodigoProduto.getText().trim()));
        c1.setNome             (                    txtNome.getText().trim());
        c1.setCodigoFornecedor (Integer.parseInt   (txtCodigoFornecedor.getText().trim()));
        c1.setFornecedor       (                    txtFornecedor.getText().trim());
        c1.setQtd              (Integer.parseInt   (txtQuantidade.getText().trim()));
        // Verifica se a operação de solicitação obteve sucesso
        if (cd.solicitarTeclado(c1)) {
          String mensagem = "Requisição de compra enviada!";
          JOptionPane.showMessageDialog(null, mensagem);
          this.dispose();
        }
      } else if (operacao == 6) { // Receber Teclado
        // Cria um objeto compra para receber os dados da do preenchimento 
        // da tela
        compra cl = new compra();
        // Cria um objeto CompraDAO para uso dos métodos de acesso
        // ao banco para os compras
        CompraDAO cd = new CompraDAO();
        // Determina os valores dos atributos do objeto compra, com os dados
        // preenchidos na tela
        // o codigo irá ser usado para determinar o registro a ser alterado
        cl.setCodigo      (                                        codigo);
        cl.setCodigoProduto    (Integer.parseInt   (txtCodigoProduto.getText().trim()));
        cl.setNome             (                    txtNome.getText().trim());
        cl.setCodigoFornecedor (Integer.parseInt   (txtCodigoFornecedor.getText().trim()));
        cl.setFornecedor       (                    txtFornecedor.getText().trim());
        cl.setQtd              (Integer.parseInt   (txtQuantidade.getText().trim()));
        
        Teclados t1 = new Teclados();
        ProdutoDAO pd = new ProdutoDAO();
        t1 = pd.buscarTeclado(cl.getCodigoProduto());
        
        // Verifica se a operação de alteração obteve sucesso
        if (cd.receberTeclado(cl, t1)) {
          String mensagem = "Estoque atualizado!";
          JOptionPane.showMessageDialog(null, mensagem);
          this.dispose();
        }
      }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDadosReposicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDadosReposicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDadosReposicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDadosReposicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDadosReposicao(0,0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lb1;
    private javax.swing.JTextField txtCodigoFornecedor;
    private javax.swing.JTextField txtCodigoProduto;
    private javax.swing.JTextField txtFornecedor;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables
}
